# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UserLogTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UserLogTest
#  pod 'SSZipArchive', '~> 2.0.2'
  pod 'objective-zip', '~> 1.0.5'
end
